// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens(eth_address, expires_at) 
VALUES($1, $2) RETURNING jti
`

type CreateAccessTokenParams struct {
	EthAddress string
	ExpiresAt  pgtype.Timestamp
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAccessToken, arg.EthAddress, arg.ExpiresAt)
	var jti pgtype.UUID
	err := row.Scan(&jti)
	return jti, err
}
