// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens(eth_address, expires_at) 
VALUES($1, $2) RETURNING jti
`

type CreateAccessTokenParams struct {
	EthAddress string
	ExpiresAt  pgtype.Timestamp
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAccessToken, arg.EthAddress, arg.ExpiresAt)
	var jti pgtype.UUID
	err := row.Scan(&jti)
	return jti, err
}

const revokeAccessToken = `-- name: RevokeAccessToken :execrows
UPDATE access_tokens SET revoked_at = CURRENT_TIMESTAMP 
WHERE jti = $1
`

func (q *Queries) RevokeAccessToken(ctx context.Context, jti pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessToken, jti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
