// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type SiweNonce struct {
	Value      string
	EthAddress pgtype.Text
	ExpiresAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	Used       pgtype.Bool
}
