// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	Jti        pgtype.UUID
	EthAddress string
	CreatedAt  pgtype.Timestamp
	ExpiresAt  pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
}

type RefreshToken struct {
	ID         pgtype.UUID
	EthAddress string
	TokenHash  string
	ExpiresAt  pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	IpAddress  pgtype.Text
	UserAgent  pgtype.Text
	DeviceName pgtype.Text
	FamilyID   pgtype.UUID
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type SiweNonce struct {
	Value      string
	EthAddress pgtype.Text
	ExpiresAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	Used       pgtype.Bool
}
