// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens(eth_address, token_hash, expires_at, device_info)
VALUES($1, $2, $3, $4) RETURNING id
`

type CreateRefreshTokenParams struct {
	EthAddress string
	TokenHash  string
	ExpiresAt  pgtype.Timestamp
	DeviceInfo pgtype.Text
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.EthAddress,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.DeviceInfo,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
