// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens(eth_address, token_hash, expires_at, ip_address, user_agent, device_name)
VALUES($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateRefreshTokenParams struct {
	EthAddress string
	TokenHash  string
	ExpiresAt  pgtype.Timestamp
	IpAddress  pgtype.Text
	UserAgent  pgtype.Text
	DeviceName pgtype.Text
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.EthAddress,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceName,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens SET revoked_at = CURRENT_TIMESTAMP 
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
