// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: siwe_nonces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeNonce = `-- name: ConsumeNonce :execrows
UPDATE siwe_nonces SET used = TRUE, eth_address=$1
WHERE value = $2 and expires_at > CURRENT_TIMESTAMP
`

type ConsumeNonceParams struct {
	EthAddress pgtype.Text
	Value      string
}

func (q *Queries) ConsumeNonce(ctx context.Context, arg ConsumeNonceParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeNonce, arg.EthAddress, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createNonce = `-- name: CreateNonce :one
INSERT INTO siwe_nonces(value, eth_address, expires_at)
values($1, $2, $3) RETURNING value
`

type CreateNonceParams struct {
	Value      string
	EthAddress pgtype.Text
	ExpiresAt  pgtype.Timestamp
}

func (q *Queries) CreateNonce(ctx context.Context, arg CreateNonceParams) (string, error) {
	row := q.db.QueryRow(ctx, createNonce, arg.Value, arg.EthAddress, arg.ExpiresAt)
	var value string
	err := row.Scan(&value)
	return value, err
}
