// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: siwe_nonces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNonce = `-- name: CreateNonce :exec
INSERT INTO siwe_nonces(value, eth_address, expires_at) 
values($1, $2, $3)
`

type CreateNonceParams struct {
	Value      string
	EthAddress pgtype.Text
	ExpiresAt  pgtype.Timestamp
}

func (q *Queries) CreateNonce(ctx context.Context, arg CreateNonceParams) error {
	_, err := q.db.Exec(ctx, createNonce, arg.Value, arg.EthAddress, arg.ExpiresAt)
	return err
}
