-- siwe_nonces table :- it holds nonces generated by system for siwe auth
CREATE TABLE IF NOT EXISTS siwe_nonces (
    value varchar(75) PRIMARY KEY,
    eth_address varchar(42),
    expires_at timestamp,
    created_at timestamp default CURRENT_TIMESTAMP,
    used boolean default false
);